version: '3.8'  # 사용할 Docker Compose 파일 버전을 지정합니다. '3.8'은 권장되는 최신 버전 중 하나입니다.
services:
  jenkins:
    container_name: jenkins  # 생성될 컨테이너의 이름을 지정합니다.
    build:  # 이미지를 빌드하기 위한 설정을 정의합니다.
      context: .  # Dockerfile이 위치한 디렉토리의 경로입니다. 여기서는 현재 디렉토리를 가리킵니다.
      dockerfile: jenkins.Dockerfile  # 사용할 Dockerfile의 이름입니다.
    ports:
      - "8888:8080"  # 호스트의 8888 포트를 컨테이너의 8080 포트에 바인딩합니다. Jenkins 웹 인터페이스에 접근하기 위해 사용됩니다.
      - "50000:50000"  # Jenkins 슬레이브 노드를 연결하기 위한 포트 매핑입니다.
    volumes:
      - ./jenkins:/var/jenkins_home  # 호스트 시스템의 './jenkins' 디렉토리를 컨테이너의 Jenkins 홈 디렉토리에 마운트합니다. Jenkins 데이터를 영구적으로 저장하기 위해 사용됩니다.
      - /usr/bin/docker:/usr/bin/docker  # 호스트의 Docker 바이너리를 컨테이너 내부로 마운트하여, 컨테이너 내부에서도 Docker 명령을 사용할 수 있게 합니다.
      - /var/run/docker.sock:/var/run/docker.sock  # 호스트의 Docker 소켓 파일을 컨테이너에 마운트합니다. 이를 통해 컨테이너 내부에서 호스트의 Docker 데몬을 제어할 수 있습니다.
