version: '3.8'  # Docker Compose 파일 버전을 지정합니다. "3.8"은 사용 가능한 최신 버전 중 하나입니다.

services:
  nowdoboss_spark:
    container_name: nowdoboss_spark  # 컨테이너의 이름을 설정합니다.
    image: bitnami/spark:latest  # 사용할 이미지
    restart: always  # 컨테이너가 어떤 이유로 종료되더라도 항상 재시작을 시도합니다.
    ports:
      - "18080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master 서비스
    environment:
      - SPARK_MODE=master  # 스파크 마스터 모드 설정
      - SPARK_RPC_AUTHENTICATION_ENABLED=no  # RPC 인증 비활성화
      - SPARK_RPC_ENCRYPTION_ENABLED=no  # RPC 암호화 비활성화
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no  # 로컬 스토리지 암호화 비활성화
      - SPARK_SSL_ENABLED=no  # SSL 비활성화


networks:
  nowdoboss_spark_net:  # 사용할 네트워크를 정의합니다.
